### PR TITLE
fix stream close

### LINKED ISSUE #1: Can't close connection server-side
Hey, I want to close connection from server-side. Here is MRE: 

```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/cristalhq/sse"
)

func main() {
	if err := http.ListenAndServe(":8080", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		stream, err := sse.UpgradeHTTP(r, w)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		defer func() { 
			if err := stream.Close(); err != nil {
				log.Printf("close stream error: %s", err)
			}
		}()

		for i := 0; i < 3; i++ {
			if err := stream.WriteEvent(
				0,
				"test",
				[]byte(fmt.Sprintf("payload %d", i)),
			); err != nil {
				log.Printf("write event error: %s", err)
			}
		}

	})); err != nil {
		log.Fatal(err)
	}
}
```

### Output 

```
2023/10/05 00:55:10 http: response.Write on hijacked connection from github.com/cristalhq/sse.(*Stream).Close (stream.go:31)
2023/10/05 00:55:10 close stream error: http: connection has been hijacked
```

I'll send out an PR soon.

### PR DESCRIPTION
**Pull request by mr-linch**
resolve #1 

 - [x] use `bufio.ReadWriter` for send close event
 - [x] add `net.Conn` to `Stream`
 - [x] add test for close

### CODE REVIEW

File: stream.go [hunk 1]
```diff
@@ -26,9 +28,11 @@ func (s *Stream) Flush() error {
 	return s.bw.Flush()
 }
 
-// Close sends close event with empth data.
+// Close sends close event with empth data and closes underlying connectioт
```
Comment (cristaloleg) [inline stream.go]:
```suggestion
// Close sends close event with empty data and closes underlying connection.
```

**Review by cristaloleg — COMMENTED** [review]
LGTM, only 1 small doc fix.

**Review by cristaloleg — APPROVED** [review]
Thanks!
